"""
Schemas for the structured disaster analysis feature.

Why this is a SEPARATE schema file/feature from chat schemas: per our
architecture decision, conversational chat (free-form streaming text) and
structured disaster analysis (classification, urgency, structured JSON)
are deliberately distinct features with different request/response
shapes and different Gemini calling patterns (streaming text vs.
structured JSON output). Mixing them into one schema would blur a
distinction that matters for how each is implemented and consumed.
"""

from enum import StrEnum

from pydantic import BaseModel, Field

from app.schemas.base import CamelCaseModel


class DisasterType(StrEnum):
    """Closed set of disaster categories the model must classify into.

    Why an enum and not a free-text string: a closed set means the
    frontend can reliably map each value to a specific icon/color/UI
    treatment (see types/domain.ts on the frontend). An open-ended string
    from the model would force the frontend to handle arbitrary,
    unpredictable category names.
    """

    EARTHQUAKE = "earthquake"
    FLOOD = "flood"
    FIRE = "fire"
    HURRICANE_CYCLONE = "hurricane_cyclone"
    TORNADO = "tornado"
    LANDSLIDE = "landslide"
    TSUNAMI = "tsunami"
    HEATWAVE = "heatwave"
    COLD_WAVE = "cold_wave"
    DROUGHT = "drought"
    INDUSTRIAL_HAZMAT = "industrial_hazmat"
    MEDICAL_EMERGENCY = "medical_emergency"
    CIVIL_UNREST = "civil_unrest"
    OTHER = "other"
    UNKNOWN = "unknown"


class UrgencyLevel(StrEnum):
    """Matches the `severity` color scale already defined on the frontend
    (tailwind.config.ts `severity` tokens) so urgency renders with the
    exact same visual language as alerts and SOS priority elsewhere in
    the app - one consistent meaning for "critical" across every feature.
    """

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class EmergencyNumber(CamelCaseModel):
    """A single relevant emergency contact for the detected situation
    and region. Kept generic (label + number) rather than a fixed set of
    fields like `police`/`fire`/`ambulance`, since the relevant set of
    numbers genuinely varies by country and disaster type (e.g. a
    poison-control number only matters for a hazmat/medical situation)."""

    label: str = Field(..., description="e.g. 'Police', 'Fire Department', 'Poison Control'")
    number: str = Field(..., description="e.g. '911', '112', '100'")


class ShelterRecommendation(CamelCaseModel):
    """A single recommended shelter, merged from real Google Places data
    (see app/services/places_service.py) - NOT generated by Gemini. We
    pass Gemini's situation analysis into the places query, then attach
    real results here. Gemini never invents shelter names or addresses.
    """

    name: str
    address: str
    latitude: float
    longitude: float
    distance_km: float | None = None
    place_id: str | None = None


class DisasterAnalysisRequest(CamelCaseModel):
    """What the frontend sends: a free-text description of the situation,
    plus optional location (needed to recommend real nearby shelters)."""

    situation: str = Field(..., min_length=1, max_length=4000)
    latitude: float | None = Field(default=None, ge=-90, le=90)
    longitude: float | None = Field(default=None, ge=-180, le=180)


class DisasterAnalysisResult(CamelCaseModel):
    """The full structured response. This is the exact shape we ask
    Gemini to produce for the AI-generated fields (everything except
    `shelters`, which we attach ourselves from real Places data after
    Gemini's response comes back).

    Inherits CamelCaseModel (unlike GeminiDisasterAnalysisOutput below)
    because THIS is the schema actually serialized to the frontend - it
    needs to produce `disasterType`, `emergencyNumbers`, etc. to match
    types/disaster-analysis.ts. GeminiDisasterAnalysisOutput, by
    contrast, is only ever consumed by our own Python code immediately
    after Gemini returns it, so it stays plain snake_case internally.
    """

    disaster_type: DisasterType
    urgency: UrgencyLevel
    summary: str = Field(
        ..., description="One or two sentence plain-language summary of the situation."
    )
    instructions: list[str] = Field(
        ..., description="Ordered, actionable emergency steps - most urgent action first."
    )
    emergency_numbers: list[EmergencyNumber]
    shelters: list[ShelterRecommendation] = Field(
        default_factory=list,
        description="Populated by our backend from real Places data, not by Gemini.",
    )
    reasoning_note: str | None = Field(
        default=None,
        description="Optional short note on why this classification/urgency was chosen - "
        "shown in UI as an expandable 'why' detail, not displayed by default.",
    )


# This is the schema shape Gemini's structured output mode is configured
# to return - everything in DisasterAnalysisResult EXCEPT `shelters`,
# since Gemini has no access to real shelter data and must not invent it.
class GeminiDisasterAnalysisOutput(BaseModel):
    disaster_type: DisasterType
    urgency: UrgencyLevel
    summary: str
    instructions: list[str]
    emergency_numbers: list[EmergencyNumber]
    reasoning_note: str | None = None
